services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: postgresql://user:password@postgres:5432/githubble_local
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    command: >
        sh -c "cp /app/app/.env.test /app/app/.env && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000"

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: githubble_local
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6379:6379"

volumes:
  postgres_data:
